  pipeline {
    agent any
         stages{
           stage('terraform-Demo') {
               steps {
                 script {
                   //dir("ta-setup")
                    //{
                      git branch: 'master', url: 'https://github.com/deepkumarchaudhary/Terraform-Tutorial-1.git'
                      sh 'cd EC2withJenkins '
                      sh 'sudo terraform --version'
                      sh 'sudo terraform init -upgrade=true -get=true -input=false -force-copy'
                      sh 'sudo terraform workspace new "terraform-demo"'
                      sh 'echo "INFO: New terraform-demo workspace added."'
                      sh 'sudo terraform workspace select terraform-demo'
                      sh 'echo "INFO: Terraform -> Planning..."'
                      sh 'sudo terraform plan -out plan_terraform -lock=true'
                      sh 'echo "INFO: Terraform -> Executing..."'
                      sh 'sudo terraform apply plan_plan_terraform'
                    //}
                  }
                }
              }
          }
        }
